version: '3'
services:
  api:
    image: peopsquik/php:latest
    volumes:
      - ./api:/var/www/html
    ports:
      - 8084:80
    env_file:
      - .env
    depends_on:
      - mysql
    command: php -S 0.0.0.0:80 -t /var/www/html/public